'use strict'

let fakeInfo = require('../seed_generator.js')

exports.seed = function(knex, Promise) {
  return knex.raw('ALTER SEQUENCE event_id_seq RESTART WITH 11')
    .then(function() {
      return knex('event').del()
    })
    .then(function () {
      return Promise.all([
        knex('event').insert({
          id: 1,
          title: 'Events coordination assistance for the Introduction to Programming with Javascript',
          location: 'Galanize - Platte',
          street: '1644 Platte Street',
          city: 'Denver',
          state: 'CO',
          zip: '80202',
          start_date: '2016-10-01',
          end_date: '2016-10-01',
          start_time: '09:00 AM',
          end_time: '5:00 PM',
          description: fakeInfo.description(),
          available_positions: 4,
          registered_volunteers: 3,
          organization_id: 9
        }),
        knex('event').insert({
          id: 2,
          title: 'Volunteers for the Platte River Clean Up',
          location: 'Confluence Park',
          street: '2200 15th Street',
          city: 'Denver',
          state: 'CO',
          zip: '80202',
          start_date: '2016-09-30',
          end_date: '2016-09-30',
          start_time: '10:00 AM',
          end_time: '12:30 PM',
          description: fakeInfo.description(),
          available_positions: 50,
          registered_volunteers: 2,
          organization_id: 10
        }),
        knex('event').insert({
          id: 3,
          title: 'Volunteers for the Block Party: Global Greengrants Fund and Global Fund for Women',
          location: 'Posner Center Commons',
          street: '1031 33rd Street',
          city: 'Denver',
          state: 'CO',
          zip: '80205',
          start_date: '2016-10-06',
          end_date: '2016-10-06',
          start_time: '11:30 AM',
          end_time: '2:00 PM',
          description: fakeInfo.description(),
          available_positions: 3,
          registered_volunteers: 0,
          organization_id: 1
        }),
        knex('event').insert({
          id: 4,
          title: 'Volunteers for the \'Government NOW! The Return of the City-State\' event',
          location: 'Seawell Grand Ballroom, Denver Performing Arts Complex',
          street: '1400 Curtis Street',
          city: 'Denver',
          state: 'CO',
          zip: '80204',
          start_date: '2016-11-05',
          end_date: '2016-11-05',
          start_time: '10:00',
          end_time: '12:00',
          description: fakeInfo.description(),
          available_positions: 4,
          registered_volunteers: 1,
          organization_id: 2
        }),
        knex('event').insert({
          id: 5,
          title: 'Volunteer Crisis Advocate',
          location: 'Pueblo StepUp Office',
          street: '1925 E Orman Avenue, Ste G-52',
          city: 'Pueblo',
          state: 'CO',
          zip: '81004',
          start_date: '2016-11-01',
          end_date: '2017-02-01',
          start_time: '9:00 AM',
          end_time: '6:00 PM',
          description: fakeInfo.description(),
          available_positions: 8,
          registered_volunteers: 2,
          organization_id: 7
        }),
        knex('event').insert({
          id: 6,
          title: 'Volunteer Canvaser',
          location: 'Roasted Espresso and Subs',
          street: '502 Colorado Avenue',
          city: 'Grand Junction',
          state: 'CO',
          zip: '81501',
          start_date: '2016-10-01',
          end_date: '2017-01-01',
          start_time: '10:00 AM',
          end_time: '2:00 PM',
          description: fakeInfo.description(),
          available_positions: 3,
          registered_volunteers: 2,
          organization_id: 8
        }),
        knex('event').insert({
          id: 7,
          title: 'Event Coordination for the WildAgain Winter Gala',
          location: 'DoubleTree - Stapleton North',
          street: '4040 Quebec Street',
          city: 'Denver',
          state: 'CO',
          zip: '80216',
          start_date: '2016-12-05',
          end_date: '2016-12-05',
          start_time: '1:30 PM',
          end_time: '11:30 PM',
          description: fakeInfo.description(),
          available_positions: 4,
          registered_volunteers: 0,
          organization_id: 3
        }),
        knex('event').insert({
          id: 8,
          title: 'Refugee Service Intern',
          location: 'Denver Rescue Mission',
          street: '3501 E. 46th Avenue',
          city: 'Denver',
          state: 'CO',
          zip: '80216',
          start_date: '2016-10-01',
          end_date: '2016-05-01',
          start_time: '9:00 AM',
          end_time: '6:00 PM',
          description: fakeInfo.description(),
          available_positions: 2,
          registered_volunteers: 0,
          organization_id: 5
        }),
        knex('event').insert({
          id: 9,
          title: 'Office & Committee Volunteers',
          location: 'Flatirons Habitat for Humanity',
          street: '2540 Frontier Avenue',
          city: 'Boulder',
          state: 'CO',
          zip: '80301',
          start_date: '2016-10-06',
          end_date: '2016-10-06',
          start_time: '9:00 AM',
          end_time: '6:00 PM',
          description: fakeInfo.description(),
          available_positions: 5,
          registered_volunteers: 3,
          organization_id: 4
        }),
        knex('event').insert({
          id: 10,
          title: 'Medical Assistant Intern',
          location: 'Denver Rescue Mission',
          street: '3501 E. 46th Avenue',
          city: 'Denver',
          state: 'CO',
          zip: '80216',
          start_date: '2016-10-01',
          end_date: '2016-05-01',
          start_time: '9:00 AM',
          end_time: '6:00 PM',
          description: fakeInfo.description(),
          available_positions: 2,
          registered_volunteers: 0,
          organization_id: 5
        })
      ])
    })
}
