'use strict'

let fakeInfo = require('../seed_generator.js')

exports.seed = function(knex, Promise) {
  return knex.raw('ALTER SEQUENCE volunteer_id_seq RESTART WITH 16')
    .then(function() {
      return knex('volunteer').del()
    })
    .then(function () {
      return Promise.all([
        knex('volunteer').insert({
          id: 1,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Denver',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"http://vickmark.com/wp-content/uploads/2011/03/20boston-headshot-photographer.jpg",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 2,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Denver',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"http://amandanelsonphoto.com/wp-content/uploads/2015/11/Rachel_Headshots_0004.jpg",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 3,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Fort Collins',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"https://upload.wikimedia.org/wikipedia/commons/6/68/Bob_Davis-headshot.jpg",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 4,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Boulder',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"http://lifeedited.com/wp-content/uploads/2012/03/graham-hill-headshot.jpg",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 5,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Pueblo',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWY0uzjcR7tsswEmkOOfZNH9q-cXUwb0y3MV-a0v9sU2AFdWHR",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 6,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Mesa',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"http://srkheadshotday.com/wp-content/uploads/Lauren_Pufpaf_Y9563_Crop32.jpg",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 7,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Pueblo',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"https://zsuttonphoto.com/wp-content/uploads/2014/12/New-Mexico-Headshot-Photography-31.jpg",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 8,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Boulder',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"https://s-media-cache-ak0.pinimg.com/236x/25/3a/bf/253abf4f1f4bc16b6dc04571f8d21624.jpg",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 9,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Castle Pines',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"http://caamedia.org/wp-content/uploads/2012/02/Harry-Headshot.jpg",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 10,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Aurora',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"http://allthingsd.com/files/2011/11/Peter-Pham-headshot.png",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 11,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Fort Collins',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"http://srkheadshotday.com/wp-content/uploads/Anna_Feenstra_Headshot_16J1097_Crop32-760x507.jpg",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 12,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Grand Junction',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"https://static1.squarespace.com/static/53dac69ae4b0ea7cdef448c2/53dacf12e4b0ea7cdef45368/56699920a128e6a6243ae428/1463589413688/Gibney-Dancer-Headshot-Sarah-Burke.jpg?format=1000w",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 13,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Denver',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"https://static1.squarespace.com/static/511526cde4b067782b69109c/51561f43e4b05239ba831e2a/517acb5fe4b041a7f26676f1/1367001954162/21-corporate-headshot-photo-ac_111002_115153_2554-12x18.JPG-1500px.JPG",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 14,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Greenley',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"https://zsuttonphoto.com/wp-content/uploads/2015/11/Trevor-Wayne-LA-Headshot-Photography-1.jpg",
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 15,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Boulder',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          picture_url:"http://i.imgur.com/DDSpcZg.jpg",
          about: fakeInfo.description(),
        })
      ])
    })
}
